### ISSUE TITLE
大佬 请教一下  命令提示菜单要修改哪个文件来把提示翻译成中文

### ISSUE THREAD

**Issue by Yakumo-Yukari** [erasin/helix-config#1]
![1112](https://github.com/user-attachments/assets/77f56020-8374-4d6f-9079-7681c0d5f082)

**Comment by erasin** [comment]
https://github.com/helix-editor/helix/blob/38faf74febf3332fb119302324bfd21229d39e14/helix-term/src/commands.rs#L278

修改 helix-term/src/commands.rs 中的 `static_commands` 找到对应的命令即可。
