### ISSUE TITLE
tutors/zh_cn文件如何使用？

### ISSUE THREAD

**Issue by asins** [erasin/helix-config#2]
在你的配置中看到有中文的帮忙文档，但我在hx中执行`:tutor`后看到的仍然是英文文档，除了执行 `hx ~/.config/helix/tutors/zh_cn`来打开外，hx还有什么快捷方法查看中文文档吗？

**Comment by asins** [comment]
> > 该功能是我自己的分支 local-dev / 具体可看 [tutor-zh](https://github.com/erasin/helix/commit/02f47083fd813093e03688562c523356795964e0) 中的功能
> 
> 在 `.config/helix/tutors/zh_cn` 文件存在的情况下,在 hx 中使用命令 `:tutor zh_cn` 打开。
> 
> 实际上是使用命令 `tutor` 打开 tutors 文件夹下的文本文件

`~/.config/helix/tutors/zh_cn` 这个文件已经存在，
```bash
❯ ll ~/.config/helix/tutors/zh_cn
-rw-r--r--  1 asins  staff    38K Nov 18 22:48 /Users/asins/.config/helix/tutors/zh_cn
```

但在hx中执行`:tutor zh_cn`无法打开文件，不同的点在于我本地的`~/.config/helix`是个软连接
```bash
❯ ll ~/.config/helix
lrwxr-xr-x  1 asins  staff    53B Nov 18 23:10 /Users/asins/.config/helix@ -> /Users/asins/Asins/Development/dotfiles/.config/helix
```

**Comment by erasin** [comment]
> 在看到你提交这个 issues 的时候，更新了 [default tutor runtime_file](https://github.com/erasin/helix/commit/02f47083fd813093e03688562c523356795964e0) 

我在linux/mac下测试软链接通过。 使用的是 `ln -s ~/dotfiles/helix ~/.config/helix` 创建的软链接。
![截图 2024-11-29 19-52-20](https://github.com/user-attachments/assets/f3626df4-7a7b-4993-b84a-573164506e3f)
可以看到补全参数
![截图 2024-11-29 20-30-01](https://github.com/user-attachments/assets/474ddfca-5e70-4d25-a70e-17e941adda42)



设定环境变量 `HELIX_RUNTIME` 为 `~/Development/dotfiles/.config/helix`，或者修改 `.config/helix` 的链接属性试试。
